POST http://localhost:4000/register
Content-Type: application/json

{
    "email": "test2",
    "password": "test2",
    "role":"admin"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "email": "test",
    "password": "test"
}

###
GET  http://localhost:4000/dashboard/products
Content-Type: application/json

###
PUT http://localhost:4000/dashboard/user/2
Content-Type: application/json

{
    "email": "test",
    "password": "test",
    "role":"admin"
}

###
POST http://localhost:4000/main/contact
Content-Type: application/json

{
    "name": "test",
    "email": "test",
    "message":"test"
}

###
GET http://localhost:4000/main/myorders/2
Content-Type: application/json

###
GET http://localhost:4000/dashboard/orders
Content-Type: application/json